name: CTW
version: ${project.version}
main: me.ollie.capturethewool.CaptureTheWool
api-version: 1.16
authors:
  - Ollie
depend:
  - HolographicDisplays
  - ProtocolLib
  - Citizens
description: Capture the Wool from Bleb.io
commands:
  ctw:
    description: penis
